name: CI Pipeline
on: 
 push:
jobs:
 build:
  runs-on: ubuntu-latest

  steps:
  - name: Checkout repository
    uses: actions/checkout@v3

  - name: Set up python
    uses: actions/setup-python@v4
    with:
     python-version: 3.11

  - name: Install dependencies
    run: |
     python -m pip install --upgrade pip
     pip install -r requirements.txt

  - name: Run main file
    run: |
     python main.py

  - name : run CML report 
    env:
     REPO_TOKEN: ${{secrets.MY_TOKEN}}
    run : |
     echo "#First Line of our report">>report.md
     echo "## Bar plots">>report.md
     echo"![](./bars.png "bar plot")">>report.md
     echo "## Line plots">>report.md
     echo"![](./lines.png "line plot")">>report.md

     cml comment create report.md